# ─────────────────────────────────────────
#  SCHOOL BACKEND — Configuración
# ─────────────────────────────────────────


# Servidor
server.port=8080


# Base de datos PostgreSQL
# Cuando corres local: apunta a localhost:5434
# Cuando corres en Docker: el host es "db" (nombre del servicio)
spring.datasource.url=jdbc:postgresql://localhost:5434/school_db
spring.datasource.username=school_user
spring.datasource.password=school_pass
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate
# validate  → solo verifica que las tablas existen (para producción)
# update    → crea/actualiza esquema automáticamente (para desarrollo)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs


# Logs
logging.level.com.school=DEBUG
logging.level.org.hibernate.SQL=DEBUG